# -*- coding: utf-8 -*-
"""Sensor Data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gwh20-Wg5kwTdTs_Wy0emZP2HA_gmfDo

Creating Dummy Data:

Generating fake sensor data for equipment to operate with, as real-time data is not available for public display.
"""

# create_dummy_data.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def generate_dummy_data(num_records=1000):
    machinery_names = np.random.choice([
        'Hot Forging Machine Press 6000T',
        'Cold Forging Machine Press 1000T',
        'Hydraulic Press 10000T',
        'Mechanical Trimming Press 110T',
        'Mechanical Coining Press 145T'
    ], num_records)
    data = {
        'machine_name': machinery_names,
        'sensor_1': np.random.normal(50, 10, num_records),
        'sensor_2': np.random.normal(60, 15, num_records),
        'sensor_3': np.random.normal(70, 20, num_records),
        'maintenance_needed': np.random.randint(0, 2, num_records)
    }
    df = pd.DataFrame(data)
    df.to_csv('sensor_data.csv', index=False)
    return df

def visualize_data(df):
    print(df.head())
    df['maintenance_needed'].value_counts().plot(kind='bar', title='Maintenance Needed Distribution')
    plt.show()

if __name__ == '__main__':
    df = generate_dummy_data()
    visualize_data(df)